mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from wee import views
from django.views.generic import RedirectView
from wee.views import Home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('home/', Home, name='home'),
    path('', RedirectView.as_view(url='home/')),
    path('', views.Home),
    path('', include('wee.urls')),
    path(r'^reviews/', include('reviews.urls')),
    path('review/', Home, name='review_was_posted'),
]

mysite/wee/urls.py
# mysite/wee/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('home/', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('post/', views.post_list, name='post_list'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/new/', views.post_new, name='post_new'),
    path('washroom/<int:pk>', views.washroom_detail, name='washroom_detail'),
    path('review/<int:pk>', views.review_washroom, name='review_washroom'),
    path('review/<int:pk>', views.washroom_detail, name='review_was_posted'),
]

mysite/wee/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone

from django.contrib.gis.db import models #not typical django model
from django.contrib.auth.models import User



# Create your models here.

class Washroom(models.Model):
	name = models.CharField(max_length=50)
	rating = models.FloatField(null=True)
	disable_access=models.BooleanField(default=False) #disable
	unisex = models.CharField(max_length=30, default='False')
	location = models.PointField()
	id = models.BigIntegerField(primary_key=True)
	type = models.CharField(max_length=30, default='unknown')
	access = models.CharField(max_length=30, default='False')
	indoor = models.CharField(max_length=30, default='False')
	diaper = models.CharField(max_length=30, default='False')
	water = models.CharField(max_length=30, default='False')
	wheelchair = models.CharField(max_length=30, default='False')
	opening_hours = models.CharField(max_length=50, default="")
	
	def get_absolute_url(self):
		return "/washrooms/%d" % self.id



class Review(models.Model): #many reviews to one washroom relationship
	washroom = models.ForeignKey(Washroom, on_delete=models.CASCADE)
	rating = models.FloatField()
	comment = models.CharField(max_length=100)

class Post(models.Model):
    # author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

mysite/wee/forms.py
from django import forms
from .models import Review

from .models import Post

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'text',)


class ReviewForm(forms.ModelForm):

	class Meta:
		model = Review
		fields = ('rating', 'comment')

mysite/wee/views.py
from django.shortcuts import render
from django.views import generic
from django.contrib.gis.geos import fromstr, Point
from django.contrib.gis.db.models.functions import Distance
from .models import Washroom
from .forms import PostForm
from django.utils import timezone
from .models import Post
from django.shortcuts import redirect
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

longitude = -122.55465
latitude = 49.163635

user_location = Point(longitude, latitude, srid=4326)

# Create your views here.
def index(request):
  context = {"home_page": "active"}
  return render(request, 'wee/index.html', context)

def about(request):
  context = {"about_page": "active"}
  return render(request, 'wee/about.html', context)

def post_list(request):
  posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
  return render(request, 'wee/post_list.html', {})

def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'blog/post_detail.html', {'post': post})

def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'wee/post_edit.html', {'form': form})

def washroom_detail(request, pk):
    washrooms = get_object_or_404(Washroom, pk=pk)
    return render(request, 'wee/washroom_detail.html', {'washrooms': washrooms})

    
@login_required
def review_washroom(request, pk):
    washrooms = get_object_or_404(Washroom, pk=pk)
    return render(request, 'wee/review_washroom.html', {'washrooms': washrooms})

# @method_decorator(login_required, name='dispatch')
# @login_required
def Home(request):
    model = Washroom

    if request.method == "POST":
        type = request.POST.get('type')
        water = request.POST.get('water')
        wheelchair = request.POST.get('wheelchair')
        indoor = request.POST.get('indoor')
        access = request.POST.get('access')
        diaper = request.POST.get('diaper')
        unisex = request.POST.get('unisex')

        qs = Washroom.objects.all()

        if (type!="Type unknown"):
            qs = qs.filter(type=type)

        if (water!="False"):
            qs = qs.filter(water=water)

        if (wheelchair!="False"):
            qs = qs.filter(wheelchair=wheelchair)

        if (indoor!="False"):
            qs = qs.filter(indoor=indoor)

        if (access!="False"):
            qs = qs.filter(access=access)

        if (diaper!="False"):
            qs = qs.filter(diaper=diaper)

        if (unisex!="False"):
            qs = qs.filter(unisex=unisex)

        qs = qs.annotate(
            distance = Distance("location", user_location)
        ).order_by("distance")
        context = {
            'queryset':qs
        }

        return render(request, 'wee/index.html', context)
    else:
        qs = Washroom.objects.annotate(
            distance = Distance("location", user_location)
        ).order_by("distance")

        context = {
            'queryset':qs
        }

        return render(request, 'wee/index.html', context)

mysite/wee/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Local Library</title>{% endblock %}
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'style.css'%}">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
  <img src="{% static "wee.png" %}">
  {% block content %}{% endblock %}



  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

mysite/wee/templates/wee/about.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="utf-8">
  <title>Washroom Details</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'about.css'%}">
  </head>

<body>
  {% include 'wee/layouts/navbar.html' %}
  <div id="content">
    <h1> <strong>Where 2 Wee locates washrooms all across British Columbia and helps you find where to wee.</strong></h1>
    <h5> Where 2 Wee uses a dataset from <a href="https://www.openstreetmap.org/#map=19/49.36677/-122.94792">OpenStreetMap</a> that includes information about the locations and opening hours of washrooms and whether a washroom is
      wheelchair-accessible, unisex, etc.</h5>
    <h5>Save your dignity today with Where 2 Wee!</h5>
    <p> All icons used in Where 2 Wee are from <a href="https://www.flaticon.com/">Flaticon</a>.
  </div>
</body>

</html>

mysite/wee/templates/wee/index.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <title>Nearby Toilets</title>
  <script src='https://api.mapbox.com/mapbox-gl-js/v1.11.1/mapbox-gl.js'></script>
  <link href='https://api.mapbox.com/mapbox-gl-js/v1.11.1/mapbox-gl.css' rel='stylesheet' />


</head>

<body>
  {% extends "wee/layouts/base.html" %}

  {% block content %} 

  {% endblock %}
</body>

</html>

mysite/wee/templates/wee/layouts/base.html
<!-- # mysite/wee/templates/wee/layouts/base.html -->

<!DOCTYPE html>
{% load static %}
{% load reviews %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Where 2 Wee</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v4.5.1/mapbox-gl-geocoder.min.js"></script>
    <link
    rel="stylesheet"
    href="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v4.5.1/mapbox-gl-geocoder.css"
    type="text/css"
    />

    <!-- <link rel="stylesheet" href="./style.css"> -->
    <link rel="stylesheet" type="text/css" href="{% static 'base.css'%}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script>
    function map(loc){
          $("#instructions").hide();
          //initializing the map
          mapboxgl.accessToken = 'pk.eyJ1IjoieHVrdWttaSIsImEiOiJja2QweWQ5amUwMWZkMnJuOTNrcHphNzEwIn0.Agj9LSXxw95ve9jAXXdKPA';
          console.log(loc)
          var map = new mapboxgl.Map({
              container: 'map',
              maxBounds: [[-123.426622, 48.970], [-122.380035, 49.48]],
              style: 'mapbox://styles/mapbox/streets-v10',
              // style: 'mapbox://styles/mapbox/light-v10',
              center: loc,
              zoom: 12,
              attributionControl: false
          });
          map.addControl(new mapboxgl.AttributionControl(), 'top-left');

          //defualt marker
          var marker = new mapboxgl.Marker()
            .setLngLat(loc)
            .addTo(map);

          //adding search bar
          map.addControl(
            new MapboxGeocoder({
            accessToken: mapboxgl.accessToken,
            mapboxgl: mapboxgl
            }),'top-left'
          );

          //add "my location" button to map
          map.addControl(
              new mapboxgl.GeolocateControl({
                  positionOptions: {
                  enableHighAccuracy: true
                  },
                  trackUserLocation: true
              }), 'top-left'
          );
          // retrieving the data from model to javascript objects
          {% if queryset %}

          var data = {
              type: 'FeatureCollection',
              features: []
          };
          {% for toilet in queryset %}

          //set toilet.rating to 0 for now until database reset


          data.features.push(
              {type: 'Feature', properties: {
                 Name: '<b>Toilet ID: {{toilet.id}}</b>'.concat("<br> <a href='{% url 'washroom_detail' toilet.id %}'>Visit Page</a>").concat("<br> <a href='{% url 'review_washroom' toilet.id %}'>Review</a>"),
                  id:{{toilet.id}} }, geometry: { type: 'Point', coordinates: [{{toilet.location.x}}, {{toilet.location.y}}] }}
              )

          {% endfor %}
          {% endif %}
          //loading the data onto the map
          map.on('load', function() {
              map.addLayer({
                  id: 'data',
                  type: 'symbol',
                  source: {
                  type: 'geojson',
                  data: data
                  },
                  layout: {
                  'icon-image': 'toilet-15',
                  'icon-allow-overlap': true
                  },
                  paint: { }
              });
          });

          var popup = new mapboxgl.Popup();

          map.on('mousemove', function(e) {
          var features = map.queryRenderedFeatures(e.point, { layers: ['data'] });
              if (!features.length) {
                  popup.remove();
                  return;
              }
              var feature = features[0];

              popup.setLngLat(feature.geometry.coordinates)
                  .setHTML(feature.properties.Name)
                  .addTo(map);

              map.getCanvas().style.cursor = features.length ? 'pointer' : '';
          });
          //right click to move default location
          map.on('contextmenu', function(e) {
            loc = [e.lngLat.lng,e.lngLat.lat]
            getRoute(loc)
            marker.remove();
            $("#instructions").hide();
            //console.log(marker._lngLat.lng)
            marker = new mapboxgl.Marker()
            .setLngLat(loc)
            .addTo(map);
          });

          //hides instructions if you click on nothing
          map.on('click', function(e) {
            $("#instructions").hide();

          });

          map.on('click', function(e) {
            var features = map.queryRenderedFeatures(e.point, { layers: ['data'] });
            if (!features.length) {
              popup.remove();
              return;
            }
            $("#instructions").show();
            var feature = features[0];
            getRoute(feature.geometry.coordinates);
          });

        // create a function to make a directions request
        function getRoute(end) {
          // make a directions request using walking profile
          // an arbitrary start will always be the same
          // only the end or destination will change
          var start = loc;
          var url = 'https://api.mapbox.com/directions/v5/mapbox/walking/'+
          start[0]+','+start[1]+';'+end[0]+','+end[1]+
          '?steps=true&geometries=geojson&access_token='+mapboxgl.accessToken;

          // make an XHR request https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest
          var req = new XMLHttpRequest();
          req.open('GET', url, true);
          req.onload = function() {
            var json = JSON.parse(req.response);
            var data = json.routes[0];
            var route = data.geometry.coordinates;
            var geojson = {
              type: 'Feature',
              properties: {},
              geometry: {
                type: 'LineString',
                coordinates: route
              }
            };
            // if the route already exists on the map, reset it using setData
            if (map.getSource('route')) {
              map.getSource('route').setData(geojson);
            } else { // otherwise, make a new request
              map.addLayer({
                id: 'route',
                type: 'line',
                source: {
                  type: 'geojson',
                  data: {
                    type: 'Feature',
                    properties: {},
                    geometry: {
                      type: 'LineString',
                      coordinates: geojson
                    }
                  }
                },
                layout: {
                  'line-join': 'round',
                  'line-cap': 'round'
                },
                paint: {
                  'line-color': '#3887be',
                  'line-width': 5,
                  'line-opacity': 0.75
                }
              });
            }
            // get the sidebar and add the instructions
            var instructions = document.getElementById('instructions');
            var steps = data.legs[0].steps;

            var tripInstructions = [];

            for (var i = 0; i < steps.length; i++) {
              tripInstructions.push('<br><li>' + steps[i].maneuver.instruction) + '</li>';
              instructions.innerHTML = '<br><span class="duration">Trip duration: <br>'
                + Math.floor(data.duration / 60) + ' min 🚶 </span>' + tripInstructions;
                //https://emojipedia.org/person-walking/
            }
          };
          req.send();
        }
      }//end of map(loc)

    </script>
    <script src="{% static 'base.js' %}"></script>
</head>

<body>
    <script>$("#instructions").hide();</script>
    {% include 'wee/layouts/navbar.html' %}
    {% block content %}{% endblock %}
    <div class="page-header">
        <a href="{% url 'post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
    </div>

    <div id='map' class="position-absolute"></div>
    <div id ="instructions"></div>
    <img id="open_sidebar" src="{% static "back.png" %}" class="toggle" style="opacity: 0.5; width:2vw; height:auto; position: fixed; right: 3%; top: 50%; z-index: 500;"  onclick="toggleNav()">
    <div id="sidebar" style="width:0;">
      <form method="POST" action="." id="filter-form">
        {% csrf_token %}
              <div class="btn-group btn-group-toggle " data-toggle="buttons" id="type-filter">
                <label class="btn btn-warning active btn-sm">
                  <input type="radio" id="unknown" autocomplete="off" name="type" value="Type unknown" checked=""> Show all types
                </label>
                <label class="btn btn-warning btn-sm">
                  <input type="radio" id="flush" autocomplete="off" name="type" value="flush"> Flush
                </label>
                <label class="btn btn-warning btn-sm">
                  <input type="radio" id="pit" autocomplete="off" name="type" value="pitlatrine"> Pit latrine
                </label>
                <label class="btn btn-warning btn-sm">
                  <input type="radio" id="chemical" autocomplete="off" name="type" value="chemical"> Chemical
                </label>
              </div>
              <div class="btn-group-toggle" data-toggle="buttons" style="margin:2px;">
                <label class="btn btn-warning btn-sm">
                  <input type="hidden" name="water" value="False"/>
                  <input type="checkbox" autocomplete="off" name="water" value="True"> Water fountain
                </label>
                <label class="btn btn-warning btn-sm">
                  <input type="hidden" name="wheelchair" value="False" />
                  <input type="checkbox" autocomplete="off" name="wheelchair" value="True"> Wheelchair
                </label>
                <label class="btn btn-warning btn-sm">
                  <input type="hidden" name="diaper" value="False" />
                  <input type="checkbox" autocomplete="off" name="diaper" value="True"> Changing table
                </label>
              </div>

              <div class="btn-group-toggle" data-toggle="buttons">
                <label class="btn btn-warning btn-sm">
                  <input type="hidden" name="unisex" value="False" />
                  <input type="checkbox" autocomplete="off" name="unisex" value="True"> Unisex
                </label>
                <label class="btn btn-warning btn-sm">
                  <input type="hidden" name="access" value="False" />
                  <input type="checkbox" autocomplete="off" name="access" value="True"> Public
                </label>
                <label class="btn btn-warning btn-sm">
                  <input type="hidden" name="indoor" value="False" />
                  <input type="checkbox" autocomplete="off" name="indoor" value="True"> Indoor
                </label>
              </div>

              <button type="submit" class="btn btn-dark" "filter_btn" id="submit-btn">
                Apply filter
              </button>
      </form>

      <div id="table-container" class="position-fixed">
        <table class="table table-hover .w-auto table"  id="toilet-table" >
          <thead class="thead-dark">
            <tr>
              <th scope="col" class= ".th-sm">NEARBY TOILETS</th>
            </tr>
          </thead>
          <tbody>
            {% for toilet in queryset %}
              <tr class="washroom">
                <td> <a href='{% url 'washroom_detail' toilet.id %}'><strong>Washroom ID: </strong>{{toilet.id}}</a><br>{{toilet.opening_hours}}</td>
              </tr>
            {% empty %}
              <tr><td style="text-align: center"><strong><h4>There are no washrooms that match the filter requirements :(</h4></strong></td></tr>
            {% endfor %}
          </tbody>
        </table>
      </div>

    </div>
</body>
</html>

mysite/wee/templates/wee/layouts/navbar.html
<!-- # mysite/wee/templates/wee/layouts/navbar.html -->

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" style="color: white;">W h e r e 2 W e e</a>
  <div id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item {{ home_page }}">
        <a class="nav-link" href="{% url 'index' %}">Home</a>
      </li>
      <li class="nav-item {{ about_page }}">
        <a class="nav-link" href="{% url 'about' %}">About</a>
      </li>
      {% if user.is_authenticated %}
      <li class="nav-item {{ logout_page }}">
        <a class="nav-link" href="{% url 'logout' %}">Log out</a>
      </li>
      {% else %}
      <li class="nav-item {{ logout_page }}">
        <a class="nav-link" href="{% url 'login' %}">Log in</a>
      </li>
      {% endif %}

    </ul>
  </div>
</nav>

mysite/wee/templates/wee/post_detail.html
{% extends 'wee/layouts/base.html' %}

{% block content %}
    <div class="post">
        {% if post.published_date %}
            <div class="date">
                {{ post.published_date }}
            </div>
        {% endif %}
        <h2>{{ post.title }}</h2>
        <p>{{ post.text|linebreaksbr }}</p>
    </div>
{% endblock %}

mysite/wee/templates/wee/post_edit.html
{% extends 'wee/layouts/base.html' %}

{% block content %}
    <h2>New post</h2>
    <p> Work in progress - creating a new post and saving it does not work right now </p>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

mysite/wee/templates/wee/review_washroom.html
<!-- # mysite/wee/templates/wee/review.html -->
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="utf-8">
  <title>Washroom Details</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'washroom_detail.css'%}">

</head>

<body>
  {% include 'wee/layouts/navbar.html' %}
  {% load reviews %}
  {% load i18n %}

  <h1>Washroom {{washrooms.id}}</h1>
  <button id="details" type="button" class="btn btn-info">
    <a href="{% url "washroom_detail" washrooms.id %}" style="color: white;">
      View Details
    </a>
  </button>
  
  <!-- <div class="container" id="toilet-info" style="width:25vw;">
    <div class="row">>
      <div class="col"> Rating</div>
      <div class="col">{{washrooms.rating}}</div>

      <div class="w-100"></div>
      <div class="col">Type</div>
      <div class="col">
        {% if "Type unknown" in washrooms.type %}
        <p> Not available </p>
        {% else %}
        {{washrooms.type}}
        {% endif %}
      </div>

      <div class="w-100"></div>
      <div class="col">Water fountain</div>
      <div class="col">
        {% if "True" in washrooms.water %}
        <img src="{% static "checkmark.png" %}" style="width:20px;">
        {% else %}
        <img src="{% static "close.png" %}" style="width:20px;">
        {% endif %}
      </div>

      <div class="w-100"></div>
      <div class="col">Wheelchair</div>
      <div class="col">
        {% if "True" in washrooms.wheelchair %}
        <img src="{% static "checkmark.png" %}" style="width:20px;">
        {% else %}
        <img src="{% static "close.png" %}" style="width:20px;">
        {% endif %}
      </div>

      <div class="w-100"></div>
      <div class="col">Changing table</div>
      <div class="col">
        {% if "True" in washrooms.diaper %}
        <img src="{% static "checkmark.png" %}" style="width:20px;">
        {% else %}
        <img src="{% static "close.png" %}" style="width:20px;">
        {% endif %}
      </div>

      <div class="w-100"></div>
      <div class="col">Unisex</div>
      <div class="col">{% if "True" in washrooms.unisex %}
        <img src="{% static "checkmark.png" %}" style="width:20px;">
        {% else %}
        <img src="{% static "close.png" %}" style="width:20px;">
        {% endif %}
      </div>

      <div class="w-100"></div>
      <div class="col">Public</div>
      <div class="col">{% if "True" in washrooms.access %}
        <img src="{% static "checkmark.png" %}" style="width:20px;">
        {% else %}
        <img src="{% static "close.png" %}" style="width:20px;">
        {% endif %}
      </div>

      <div class="w-100"></div>
      <div class="col">Indoor</div>
      <div class="col">{% if "True" in washrooms.indoor %}
        <img src="{% static "checkmark.png" %}" style="width:20px;">
        {% else %}
        <img src="{% static "close.png" %}" style="width:20px;">
        {% endif %}
      </div>
    </div>
  </div> -->

{% block content %}

	{% load reviews i18n %}
    {% load reviews %}



<!-- 	<script>
		var starRatingControls = new StarRating('#id_rating', {clearable: false, showText: {{ show_rating_text|yesno:"true,false" }}, initialText: '{% trans "Select a rating" %}'});

	</script> -->
	
	<!-- {% get_review_form for washrooms as form %} -->
	<table>
		<form action="{% review_form_target %}" method="post">{% csrf_token %}
		  {% if next %}
		    <input type="hidden" name="next" value="{{ next }}"/>
		  {% endif %}
		  {% for field in form %}
		    {% if field.is_hidden %}
		      {{ field }}
		    {% else %}
		      {% if field.errors %}{{ field.errors }}{% endif %}
		      <p{% if field.errors %} class="error"{% endif %}{% ifequal field.name "honeypot" %} style="display:none;"{% endifequal %}>
		        {{ field.label_tag }} {{ field }}
		      </p>
		    {% endif %}
		  {% endfor %}
		  <p class="submit">
		    <td colspan="2">
	        	<input type="submit" name="post" class="submit-post" value="{% trans "Post" %}"/>
	        	<input type="button" value="Back" onclick="history.back()"/>
				<input type="hidden" name="next" value="{% url 'review_was_posted' %}" />
	      	</td>
		  </p>
		</form>
	</table>

	{{ form.media }}
	<style>
		.gl-star-rating[data-star-rating] { display: inline-block; }
	</style>
	<script>
		var starRatingControls = new StarRating('#id_rating', {clearable: false, showText: {{ show_rating_text|yesno:"true,false" }}, initialText: '{% trans "Select a rating" %}'});

	</script>

<!-- 	  <form action="{% review_form_target %}" method="post">
	    {% csrf_token %}
	    {{ form }}
	    <tr>
	      <td colspan="2">
	        <input type="submit" name="submit" value="Post">
			<input type="hidden" name="next" value="{% url 'review_was_posted' %}" />
	      </td>
	    </tr>
	  </form> -->

{% endblock %}

  <!-- <button type="button" class="btn btn-info">Review this washroom</button> -->
</body>

</html>